project:
  type: website

website:
  title: "Mike O'Brien"
  navbar:
    background: primary
    left:
      - href: mailto:mike@obrien.page
        icon: envelope
      - href: https://github.com/mhpob
        icon: github
      - text: Research
        file: research/index.qmd
      - text: Packages
        file: research/packages.qmd
      - text: Blog
        file: blog/index.qmd
      - text: Rugby
        file: rugby/index.qmd
      

format:
  html:
    theme: darkly
    toc: true
    link-external-newwindow: true

execute: 
  freeze: auto

resources: 
  - CNAME