project:
  type: website
  execute-dir: project

website:
  title: "Mike O'Brien"
  navbar:
    background: primary
    left:
      - href: mailto:mikeob9@gmail.com
        icon: envelope
      - href: https://github.com/mhpob
        icon: github
      - href: https://twitter.com/ruggafish
        icon: twitter
      - file: research/research_list.qmd
        text: Research
      - file: research/packages.qmd
        text: Packages
      - file: spoil_land_park/find_parcels_view.qmd
        text: Interesting parcels
      - file: henrico_parcel_age.qmd
        text: Henrico building ages

      

format:
  html:
    theme: lux
    css: custom.scss
    toc: true

execute: 
  freeze: auto

resources: 
  - CNAME