---
title: "Research"
---

[{{< fa brands github size=2xl >}}](https://github.com/mhpob) [{{< ai google-scholar size=2xl >}}](https://scholar.google.com/citations?user=IMIq9P4AAAAJ&hl=en) [{{< ai orcid size=2xl >}}](https://orcid.org/0000-0003-1420-6395) [{{< ai publons size=2xl >}}](https://www.webofscience.com/wos/author/record/ABF-9080-2021) [{{< ai stackoverflow size=2xl >}}](https://stackoverflow.com/users/7496818/mike-obrien) [{{< ai zotero size=2xl >}}](https://www.zotero.org/mhpobrien) 

## Current

Check out our current research offshore of Ocean City, MD:\
[https://tailwinds.umces.edu/](https://tailwinds.umces.edu/)

What's going on? A haiku:

> Turbines going up\
  But how will the fish react?\
  Observe: pots and hooks

## Peer-reviewed manuscripts

{{< ai open-access size=lg color=green >}} Rothermel, E.R., *O'Brien M.H.P.*, Best, J.E., Fox, D.A., Gahagan, B.I., Higgs, A.L., Park, I.A., Wippelhauser, G., Secor, D.H., 2024. An Eulerian perspective on habitat models of striped bass occurrence in an offshore wind development area. ICES Journal of Marine Science, fsad212. [https://doi.org/10.1093/icesjms/fsad212](https://doi.org/10.1093/icesjms/fsad212)

{{< ai open-access size=lg color=green >}} Secor, D.H., Bailey, H., Carroll, A., Lyubchich, V., *O'Brien, M.H.P.*, Wiernicki, C.J., 2021. Diurnal vertical movements in black sea bass (Centropristis striata): Endogenous, facultative, or something else? Ecosphere 12, e03616. [https://doi.org/10.1002/ecs2.3616](https://doi.org/10.1002/ecs2.3616)

{{< ai closed-access size=lg color=pink >}} Secor, D.H., *O’Brien, M.H.P.*, Coleman, N., Horne, A., Park, I., Kazyak, D.C., Bruce, D.G., Stence, C., 2021. Atlantic Sturgeon Status and Movement Ecology in an Extremely Small Spawning Habitat: The Nanticoke River-Marshyhope Creek, Chesapeake Bay. Reviews in Fisheries Science & Aquaculture 1–20. [https://doi.org/10.1080/23308249.2021.1924617](https://doi.org/10.1080/23308249.2021.1924617)

{{< ai open-access size=lg color=green >}} *O’Brien, M.H.P.*, Secor, D.H., 2021. Influence of thermal stratification and storms on acoustic telemetry detection efficiency: a year-long test in the US Southern Mid-Atlantic Bight. Animal Biotelemetry 9, 8. [https://doi.org/10.1186/s40317-021-00233-3](https://doi.org/10.1186/s40317-021-00233-3)

{{< ai open-access size=lg color=green >}} Itakura, H., *O’Brien, M.H.P.*, Secor, D., 2021. Tracking oxy-thermal habitat compression encountered by Chesapeake Bay striped bass through acoustic telemetry. ICES Journal of Marine Science fsab009. [https://doi.org/10.1093/icesjms/fsab009](https://doi.org/10.1093/icesjms/fsab009)

{{< ai open-access size=lg color=green >}} Secor, D.H., *O’Brien, M.H.P.*, Gahagan, B.I., Fox, D.A., Higgs, A.L., Best, J.E., 2020. Multiple spawning run contingents and population consequences in migratory striped bass Morone saxatilis. PLOS ONE 15(11): e0242797 [https://doi.org/10.1371/journal.pone.0242797](https://doi.org/10.1371/journal.pone.0242797)

{{< ai open-access size=lg color=green >}} Rothermel, E.R., Balazik, M.T., Best, J.E., Fox, D.A., Gahagan, B.I., Haulsee, D.E., Higgs, A.L., *O’Brien, M.H.P.*, Oliver, M.J., Park, I.A., and Secor, D.H. 2020. Comparative migration ecology of striped bass and Atlantic sturgeon in the US Southern Mid-Atlantic Bight flyway. PLOS ONE 15(6): e0234442. [https://doi.org/10.1371/journal.pone.0234442](https://doi.org/10.1371/journal.pone.0234442)

{{< ai open-access size=lg color=green >}} Secor, D.H., *O'Brien, M.H.P*, Gahagan, B.I., Watterson, J.C., and Fox, D. 2020. Differential migration in Chesapeake Bay striped bass. PLOS ONE 15(5): e0233103. [https://doi.org/10.1371/journal.pone.0233103](https://doi.org/10.1371/journal.pone.0233103)

{{< ai open-access size=lg color=green >}} Wiernicki, C.J., *O’Brien, M.H.P.*, Zhang F, Lyubchich V, Li M, Secor, D.H., 2020. The recurring impact of storm disturbance on black sea bass (Centropristis striata) movement behaviors in the Mid-Atlantic Bight. PLOS ONE 15(12): e0239919. [https://doi.org/10.1371/journal.pone.0239919](https://doi.org/10.1371/journal.pone.0239919)

{{< ai open-access size=lg color=green >}} Secor, D.H., Zhang, F., *O’Brien, M.H.P.* and Li, M. 2019. Ocean destratification and fish evacuation caused by a Mid-Atlantic tropical storm. ICES Journal of Marine Science, 76(2). [https://doi.org/10.1093/icesjms/fsx241](https://doi.org/10.1093/icesjms/fsx241)

{{< ai open-access size=lg color=green >}} Wingfield, J.E., *O’Brien, M.*, Lyubchich, V., Roberts, J.J., Halpin, P.N., Rice, A.N. and Bailey, H., 2017. Year-round spatiotemporal distribution of harbour porpoises within and around the Maryland wind energy area. PLOS ONE, 12(5), p.e0176653 [https://doi.org/10.1371/journal.pone.0176653](https://doi.org/10.1371/journal.pone.0176653)

## Open reports
Secor, D, *M O’Brien*, E Rothermel, C Wiernicki, and H Bailey. “Movement and Habitat Selection by Migratory Fishes within the Maryland Wind Energy Area and Adjacent Reference Sites.” Sterling (VA): U.S. Department of the Interior, Bureau of Ocean Energy Management, Office of Renewable Energy Programs, 2020. URL: [https://espis.boem.gov/final%20reports/BOEM_2020-030.pdf](https://espis.boem.gov/final%20reports/BOEM_2020-030.pdf)


## Curated datasets
Rothermel, Ella, *Michael O’Brien*, and David Secor. “Data from: Comparative Migration Ecology of Striped Bass and Atlantic Sturgeon in the US Southern Mid-Atlantic Bight Flyway.” Dryad, 2020. [https://doi.org/10.5061/DRYAD.6HDR7SQX3](https://doi.org/10.5061/DRYAD.6HDR7SQX3).

*O’Brien, Michael*, David Secor, Benjamin Gahagan, Dewayne Fox, Amanda Higgs, and Jessica Best. “Data from: Multiple Spawning Run Behavior and Population Consequences in Migratory Striped Bass Morone Saxatilis.” Dryad, 2020. [https://doi.org/10.5061/DRYAD.6HDR7SQXT](https://doi.org/10.5061/DRYAD.6HDR7SQXT).
