---
title: "Research"
---

[{{< ai google-scholar size=2xl >}}](https://scholar.google.com/citations?user=IMIq9P4AAAAJ&hl=en) [{{< ai orcid size=2xl >}}](https://orcid.org/0000-0003-1420-6395) [{{< ai publons size=2xl >}}](https://www.webofscience.com/wos/author/record/ABF-9080-2021)


## Reviewed manuscripts

Secor, D.H., Bailey, H., Carroll, A., Lyubchich, V., <strong>O'Brien, M.H.P.</strong>, Wiernicki, C.J., 2021. Diurnal vertical movements in black sea bass (Centropristis striata): Endogenous, facultative, or something else? Ecosphere 12, e03616. [https://doi.org/10.1002/ecs2.3616](https://doi.org/10.1002/ecs2.3616)

Secor, D.H., **O’Brien, M.H.P.**, Coleman, N., Horne, A., Park, I., Kazyak, D.C., Bruce, D.G., Stence, C., 2021. Atlantic Sturgeon Status and Movement Ecology in an Extremely Small Spawning Habitat: The Nanticoke River-Marshyhope Creek, Chesapeake Bay. Reviews in Fisheries Science & Aquaculture 1–20. [https://doi.org/10.1080/23308249.2021.1924617](https://doi.org/10.1080/23308249.2021.1924617)

**O’Brien, M.H.P.**, Secor, D.H., 2021. Influence of thermal stratification and storms on acoustic telemetry detection efficiency: a year-long test in the US Southern Mid-Atlantic Bight. Animal Biotelemetry 9, 8. [https://doi.org/10.1186/s40317-021-00233-3](https://doi.org/10.1186/s40317-021-00233-3)

Itakura, H., **O’Brien, M.H.P.**, Secor, D., 2021. Tracking oxy-thermal habitat compression encountered by Chesapeake Bay striped bass through acoustic telemetry. ICES Journal of Marine Science fsab009. [https://doi.org/10.1093/icesjms/fsab009](https://doi.org/10.1093/icesjms/fsab009)

Secor D.H., **O’Brien M.H.P.**, Gahagan B.I., Fox D.A., Higgs A.L., Best J.E., 2020. Multiple spawning run contingents and population consequences in migratory striped bass Morone saxatilis. PLoS ONE 15(11): e0242797 [https://doi.org/10.1371/journal.pone.0242797](https://doi.org/10.1371/journal.pone.0242797)

Rothermel, E.R., Balazik, M.T., Best, J.E., Fox, D.A., Gahagan, B.I., Haulsee, D.E., Higgs, A.L., **O’Brien, M.H.P.**, Oliver, M.J., Park, I.A., and Secor, D.H. 2020. Comparative migration ecology of striped bass and Atlantic sturgeon in the US Southern Mid-Atlantic Bight flyway. Plos One 15(6): e0234442. [https://doi.org/10.1371/journal.pone.0234442](https://doi.org/10.1371/journal.pone.0234442)

Secor, D.H., **M.H.P O Brien**, B.J. Gahagan, J.C Watterson, and D. Fox. 2020. Differential migration in Chesapeake Bay striped bass. PloS ONE 15(5): e0233103. [https://doi.org/10.1371/journal.pone.0233103](https://doi.org/10.1371/journal.pone.0233103)

Wiernicki CJ, **O’Brien MHP**, Zhang F, Lyubchich V, Li M, Secor DH, 2020. The recurring impact of storm disturbance on black sea bass (Centropristis striata) movement behaviors in the Mid-Atlantic Bight. PLoS ONE 15(12): e0239919. [https://doi.org/10.1371/journal.pone.0239919](https://doi.org/10.1371/journal.pone.0239919)

Secor, D.H., Zhang, F., **O’Brien, M.H.P.** and Li, M. 2019. Ocean destratification and fish evacuation caused by a Mid-Atlantic tropical storm. ICES Journal of Marine Science, 76(2). [https://doi.org/10.1093/icesjms/fsx241](https://doi.org/10.1093/icesjms/fsx241)

Wingfield, J.E., **O’Brien, M.**, Lyubchich, V., Roberts, J.J., Halpin, P.N., Rice, A.N. and Bailey, H., 2017. Year-round spatiotemporal distribution of harbour porpoises within and around the Maryland wind energy area. PloS ONE, 12(5), p.e0176653 [https://doi.org/10.1371/journal.pone.0176653](https://doi.org/10.1371/journal.pone.0176653)

## Curated datasets