---
title: "Create: Interesting parcels and their access points"
author:
  - name: Mike O'Brien
    email: mikeob9@gmail.com
---


Owners of Henrico parcels can be seen if clicking on "Real Estate Data" in the [GIS Viewer](https://portal.henrico.us/GISViewer/), but don't seem to be available via the [GeoData site](https://data-henrico.opendata.arcgis.com/). Luckily the [real estate search](https://realestate.henrico.us/) is API-friendly.

```{r}
#| message: false
#| warning: false
library(httr); library(rvest)

henrico_owner <- function(gpin){
  url <- paste0(
    'https://realestate.henrico.us/ords/cam/f?p=510101:5:::NO::P5_PARCEL_ID,P5_SEARCH_TYPE:',
    gpin,
    ',0'
  )
  
  real_estate_info <- GET(url)
  
  data.frame(
    gpin = gpin,
    owner = real_estate_info|> 
    content() |> 
    html_element(
      xpath = 'body/form/table[3]/tr/td[1]/table[1]/tr/td[2]/table/tr[2]/td/table/tr[7]/td[2]') |> 
    html_text()
  )
}
```

Filter Varina parcels by voting districts.
```{r}
#| message: false
#| warning: false
library(dplyr);library(arrow); library(sf); library(geoarrow)

districts <- read_sf('data/geo/voting precincts/voting_precincts.shp',
                     query = "select * from Voting_Precincts where
                     PRECINCT_N = 'Montrose' OR
                     PRECINCT_N = 'Adams'") |> 
  st_union()


varina <- open_dataset('data/geo/henrico_parcels.parquet') |>
  filter(MAGISTER_1 == 'Varina') |> 
  geoarrow_collect_sf()

montrose <- st_intersection(varina, st_transform(districts, st_crs(varina)))

```


```{r}
#| eval: false
library(future.apply)
plan(multisession)

parcel_owners <- future_lapply(montrose$GPIN, henrico_owner) |> 
  bind_rows()

write.csv(parcel_owners, 'data/gep/montrose_parcel_owners.csv')
```

```{r}
parcel_owners <- read.csv('data/montrose_parcel_owners.csv')
```


```{r}
parcels <- parcel_owners |> 
  filter(grepl('^RICHMOND (DEVELOPMENT|HOMES)|CHESAPEAKE BAY', owner) |
           gpin %in% c('808-717-3392',
                       '807-717-7478',
                       '807-717-1292',
                       '806-718-7211',
                       '806-717-5171',
                       '806-717-1889',
                       '808-717-6457'))
parcels <- montrose |> 
  right_join(parcels, by = c('GPIN' = 'gpin')) |> 
  mutate(owner = ifelse(is.na(owner), 'GILLIES CREEK INDUSTRIAL RECYCLING LLC',
                        owner))

write_sf(parcels, 'data/geo/parcels.gpkg')
```


```{r}
access_pts <- data.frame(
  matrix(
    c(-77.385338, 37.523702, "richmond development, inc",
      -77.392297, 37.525004, 'ivester, david',
      -77.384438, 37.529007, 'montrose, graham',
      -77.383748, 37.525491, 'richmond development, inc',
      -77.382565,  37.525508, 'richmond development, inc',
      -77.383011, 37.522102, 'herrera martinez yumira',
      -77.394685, 37.525799, 'workmens cemetery',
      -77.380802, 37.527383, 'virginia tech'
    ),
    ncol = 3, byrow = T
  )
) |> 
  st_as_sf(coords = c('X1', 'X2'), crs = 4326)

write_sf(access_pts, 'data/geo/access_pts.gpkg')
```

